//Header
//! import "Header\Basic.j"
//! import "Header\Constants.j"
//! import "Header\Loading.j"
//! import "Header\Primitive.j"

//! import "Header\Math.j"

//! import "Header\Memory.j"

//! import "Header\Model.j"
//! import "Header\Preload.j"

//! import "Header\BoolExpr.j"
//! import "Header\Buff.j"
//! import "Header\Dialog.j"
//! import "Header\LimitOp.j"
//! import "Header\Multiboard.j"
//! import "Header\Region.j"
//! import "Header\Timer.j"
//! import "Header\Trigger.j"
//! import "Header\WeatherEffect.j"

//! import "Header\Event.j"
//! import "Header\Group.j"
//! import "Header\Spot.j"

//! import "Header\EventCombination.j"
//! import "Header\Order.j"
//! import "Header\StringData.j"

//! import "Header\Destructable.j"
//! import "Header\ItemType.j"
//! import "Header\Item.j"
//! import "Header\ItemObjectCreation.j"
//! import "Header\Misc.j"
//! import "Header\User.j"

//! import "Header\Camera.j"
//! import "Header\Sound.j"
//! import "Header\TextTag.j"

//! import "Header\UnitType.j"
//! import "Header\Unit.j"
//! import "Header\UnitObjectCreation.j"

//! import "Header\Effect.j"
//! import "Header\Game.j"
//! import "Header\Lightning.j"
//! import "Header\Missile.j"
//! import "Header\Spell.j"
//! import "Header\SpellObjectCreation.j"
//Commands
//! import "Commands\CharacterSpeech.j"
//Misc
//! import "Misc\ActUpgrades.j"
//! import "Misc\AfterIntro.j"
//! import "Misc\Artifact.j"
//! import "Misc\BrazierOracle.j"
//! import "Misc\CameraQuickPosition.j"
//! import "Misc\DefenderSpawn.j"
//! import "Misc\Difficulty.j"
//! import "Misc\Drop.j"
//! import "Misc\Explosive.j"
//! import "Misc\GoldCoin.j"
//! import "Misc\HeroRevival.j"
//! import "Misc\Hint.j"
//! import "Misc\HorseRide.j"
//! import "Misc\Infoboard.j"
//! import "Misc\Infocard.j"
//! import "Misc\Lumber.j"
//! import "Misc\Nullboard.j"
//! import "Misc\Rune.j"
//! import "Misc\Snowmen.j"
//! import "Misc\SpellPurchase.j"
//! import "Misc\UnitNameTag.j"
//! import "Misc\VictoryRush.j"
//! import "Misc\Waypoint.j"
//! import "Misc\Zoom.j"
//! import "Misc\rpgcam.j"
	//CreepBuffs
	//! import "Misc\CreepBuffs\MarkOfThePaw.j"

//! import "Misc\Act.j"
//! import "Misc\HeroSelection.j"
//! import "Misc\Intro.j"
//! import "Misc\Level.j"
//! import "Misc\OptionsBoard.j"
//! import "Misc\UnitStatus.j"

//! import "Misc\CreepSet.j"
//! import "Misc\Spawn.j"
//Speeches
//! import "Speeches\AxeFighter.j"
//! import "Speeches\Balduir.j"
//Spells
//! import "Spells\Misc\ArcticBlink\ArcticBlink.j"
//! import "Spells\Misc\BigHealingWave\BigHealingWave.j"
//! import "Spells\Misc\BurnLumber\BurnLumber.j"
//! import "Spells\Misc\BurningSpirit\BurningSpirit.j"
//! import "Spells\Misc\BurningSpiritMeteorite\BurningSpiritMeteorite.j"
//! import "Spells\Misc\CoreFusion\CoreFusion.j"
//! import "Spells\Misc\DarkAttack\DarkAttack.j"
//! import "Spells\Misc\FountainAura\FountainAura.j"
//! import "Spells\Misc\FountainHeal\FountainHeal.j"
//! import "Spells\Misc\FrostAttack\FrostAttack.j"
//! import "Spells\Misc\Invisibility\Invisibility.j"
//! import "Spells\Misc\Invulnerability\Invulnerability.j"
//! import "Spells\Misc\Lapidation\Lapidation.j"
//! import "Spells\Misc\LightningAttack\LightningAttack.j"
//! import "Spells\Misc\RefreshMana\RefreshMana.j"
//! import "Spells\Misc\RevealAura\RevealAura.j"
//! import "Spells\Misc\TorchLight\TorchLight.j"
	//Act1
	//! import "Spells\Act1\Boost\Boost.j"
	//! import "Spells\Act1\ChaosBall\ChaosBall.j"
	//! import "Spells\Act1\EnergyCharge\EnergyCharge.j"
	//! import "Spells\Act1\FuzzyAttack\FuzzyAttack.j"
	//! import "Spells\Act1\GreenNova\GreenNova.j"
	//! import "Spells\Act1\Heal\Heal.j"
	//! import "Spells\Act1\HealExplosion\HealExplosion.j"
	//! import "Spells\Act1\IceArrows\IceArrows.j"
	//! import "Spells\Act1\LightningShield\LightningShield.j"
	//! import "Spells\Act1\LunarRestoration\LunarRestoration.j"
	//! import "Spells\Act1\Purge\Purge.j"
	//! import "Spells\Act1\SoakingPoison\SoakingPoison.j"
	//! import "Spells\Act1\Stampede\Stampede.j"
	//Act2
	//! import "Spells\Act2\Barrage\Barrage.j"
	//! import "Spells\Act2\BouncyBomb\BouncyBomb.j"
	//! import "Spells\Act2\BurningOil\BurningOil.j"
	//! import "Spells\Act2\ChainLightning\ChainLightning.j"
	//! import "Spells\Act2\Cleavage\Cleavage.j"
	//! import "Spells\Act2\ColdResistance\ColdResistance.j"
	//! import "Spells\Act2\DeathAxe\DeathAxe.j"
	//! import "Spells\Act2\DrumRoll\DrumRoll.j"
	//! import "Spells\Act2\EnvenomedSpears\EnvenomedSpears.j"
	//! import "Spells\Act2\Knockout\Knockout.j"
	//! import "Spells\Act2\Medipack\Medipack.j"
	//! import "Spells\Act2\MutingShout\MutingShout.j"
	//! import "Spells\Act2\Realplex\Realplex.j"
	//! import "Spells\Act2\SerpentWard\SerpentWard.j"
	//! import "Spells\Act2\SpiritWolves\SpiritWolves.j"
	//! import "Spells\Act2\Stormbolt\Stormbolt.j"
	//! import "Spells\Act2\SummonMinions\SummonMinions.j"
	//Hero
	//! import "Spells\Hero\ArcticWolf\ArcticWolf.j"
	//! import "Spells\Hero\Amaterasu\Amaterasu.j"
	//! import "Spells\Hero\Avatar\Avatar.j"
	//! import "Spells\Hero\BattleRage\BattleRage.j"
	//! import "Spells\Hero\Bubble\Bubble.j"
	//! import "Spells\Hero\Conflagration\Conflagration.j"
	//! import "Spells\Hero\Crippling\Crippling.j"
	//! import "Spells\Hero\DeprivingShock\DeprivingShock.j"
	//! import "Spells\Hero\Doppelganger\Doppelganger.j"
	//! import "Spells\Hero\EmphaticBite\EmphaticBite.j"
	//! import "Spells\Hero\FairysTears\FairysTears.j"
	//! import "Spells\Hero\GarmentsOfTheSalamander\GarmentsOfTheSalamander.j"
	//! import "Spells\Hero\HandOfNature\HandOfNature.j"
	//! import "Spells\Hero\HopNDrop\HopNDrop.j"
	//! import "Spells\Hero\Infection\Infection.j"
	//! import "Spells\Hero\KhakiRecovery\KhakiRecovery.j"
	//! import "Spells\Hero\ManaLaser\ManaLaser.j"
	//! import "Spells\Hero\NegationWave\NegationWave.j"
	//! import "Spells\Hero\PandaPaw\PandaPaw.j"
	//! import "Spells\Hero\RazorBlade\RazorBlade.j"
	//! import "Spells\Hero\RelentlessShiver\RelentlessShiver.j"
	//! import "Spells\Hero\RigorMortis\RigorMortis.j"
	//! import "Spells\Hero\SakeBomb\SakeBomb.j"
	//! import "Spells\Hero\SleepingDraft\SleepingDraft.j"
	//! import "Spells\Hero\SummonPolarBear\SummonPolarBear.j"
	//! import "Spells\Hero\Susanoo\Susanoo.j"
	//! import "Spells\Hero\TempestStrike\TempestStrike.j"
	//! import "Spells\Hero\Tsukuyomi\Tsukuyomi.j"
	//! import "Spells\Hero\WanShroud\WanShroud.j"
	//! import "Spells\Hero\WaterBindings\WaterBindings.j"
	//! import "Spells\Hero\Zodiac\Zodiac.j"
	//Artifacts
	//! import "Spells\Artifacts\BatSwarm\BatSwarm.j"
	//! import "Spells\Artifacts\MagicBottle\MagicBottle.j"
	//! import "Spells\Artifacts\RedwoodValkyrie\RedwoodValkyrie.j"
	//! import "Spells\Artifacts\SapphireblueDagger\SapphireblueDagger.j"
	//! import "Spells\Artifacts\SilentBoots\SilentBoots.j"
	//! import "Spells\Artifacts\TaintedLeaf\TaintedLeaf.j"
	//! import "Spells\Artifacts\Thunderbringer\Thunderbringer.j"
	//! import "Spells\Artifacts\VioletEarring\VioletEarring.j"
	//! import "Spells\Artifacts\Vomit\Vomit.j"
	//! import "Spells\Artifacts\WhiteStaff\WhiteStaff.j"
	//Purchasable
	//! import "Spells\Purchasable\Barrier\Barrier.j"
	//! import "Spells\Purchasable\Blizzard\Blizzard.j"
	//! import "Spells\Purchasable\ChillyBreath\ChillyBreath.j"
	//! import "Spells\Purchasable\FlameTongue\FlameTongue.j"
	//! import "Spells\Purchasable\Fireball\Fireball.j"
	//! import "Spells\Purchasable\FrozenStar\FrozenStar.j"
	//! import "Spells\Purchasable\GhostSword\GhostSword.j"
	//! import "Spells\Purchasable\HeatExplosion\HeatExplosion.j"
	//! import "Spells\Purchasable\IceBlock\IceBlock.j"
	//! import "Spells\Purchasable\Severance\Severance.j"
	//! import "Spells\Purchasable\SnowySphere\SnowySphere.j"
	//! import "Spells\Purchasable\VividMeteor\VividMeteor.j"
	//! import "Spells\Purchasable\WarmthMagnetism\WarmthMagnetism.j"
	//Item
	//! import "Spells\Item\EmergencyProvision\EmergencyProvisions.j"
	//! import "Spells\Item\FireWater\FireWater.j"
	//! import "Spells\Item\HerbalOintment\HerbalOintment.j"
	//! import "Spells\Item\IceTea\IceTea.j"
	//! import "Spells\Item\Meat\Meat.j"
	//! import "Spells\Item\TropicalRainbow\TropicalRainbow.j"
		//Act1
		//! import "Spells\Item\Act1\BoomerangStone\BoomerangStone.j"
		//! import "Spells\Item\Act1\EyeOfTheFlame\EyeOfTheFlame.j"
		//! import "Spells\Item\Act1\ScrollOfProtection\ScrollOfProtection.j"
		//! import "Spells\Item\Act1\TeleportScroll\TeleportScroll.j"
		//Act2
//Items
//! import "Items\MeteoriteShard.j"
	//Act1
	//! import "Items\Act1\Mallet\Mallet.j"
	//! import "Items\Act1\PenguinFeather\PenguinFeather.j"
	//! import "Items\Act1\RabbitsFoot\RabbitsFoot.j"
	//! import "Items\Act1\RamblersStick\RamblersStick.j"
	//Act2
	//! import "Items\Act2\GruntAxe\GruntAxe.j"
	//! import "Items\Act2\RobynsHood\RobynsHood.j"
	//Act3
	//! import "Items\Act3\ElfinDagger\ElfinDagger.j"
	//! import "Items\Act3\SpearOfTheDefender\SpearOfTheDefender.j"
//System
//! import "System\Meteorite.j"
//Units
//! import "Units\FlyingPenguin.j"
//! import "Units\Library.j"
//! import "Units\Sebastian.j"
//AI
//! import "AI\Boost.j"
//! import "AI\BouncyBomb.j"
//! import "AI\BurningSpirit.j"
//! import "AI\ChaosBall.j"
//! import "AI\Heal.j"
//! import "AI\HealExplosion.j"
//! import "AI\Knockout.j"
//! import "AI\Medipack.j"
//! import "AI\Purge.j"
	//Header
	//! import "AI\Header\CastSpell.j"

//Init
//! import "Init\AI.j"
//! import "Init\Commands.j"
//! import "Init\Header.j"
//! import "Init\Items.j"
//! import "Init\Misc.j"
//! import "Init\Other.j"
//! import "Init\Speeches.j"
//! import "Init\Spells.j"
//! import "Init\Units.j"

//! import "Init\Main.j"
//Debug
//! import "Debug\loadmem.j"
//! import "Debug\say.j"
//! import "Debug\setid.j"
//! import "Debug\sethp.j"
//! import "Debug\setlvl.j"
//! import "Debug\memtabletest.j"
//! import "Debug\herospell.j"