static UnitType SUMMON_UNIT_TYPE
    
    
static method Init_obj_summonUnitType takes nothing returns nothing
    local ObjThread t = ObjThread.Create("D:\\Warcraft III\\Maps\\DWC\\Scripts\\Misc\\Pharmacy.page\\Pharmacy.struct\\EyeOfTheFlame.page\\EyeOfTheFlame.struct\\summonUnitType.wc3unit")
    set thistype.SUMMON_UNIT_TYPE = UnitType.Create('uEoF')
    call thistype.SUMMON_UNIT_TYPE.Classes.Add(UnitClass.WARD)
    call thistype.SUMMON_UNIT_TYPE.Scale.Set(1.25)
    call thistype.SUMMON_UNIT_TYPE.Impact.Z.Set(93.75)
    call thistype.SUMMON_UNIT_TYPE.Outpact.Z.Set(351.5625)
    call thistype.SUMMON_UNIT_TYPE.Armor.Set(0)
    call thistype.SUMMON_UNIT_TYPE.Armor.Type.Set(Attack.ARMOR_TYPE_LARGE)
    call thistype.SUMMON_UNIT_TYPE.Life.Set(65)
    call thistype.SUMMON_UNIT_TYPE.Life.SetBJ(65)
    call thistype.SUMMON_UNIT_TYPE.LifeRegeneration.Set(0)
    call thistype.SUMMON_UNIT_TYPE.SightRange.Set(1200)
    call thistype.SUMMON_UNIT_TYPE.SightRange.SetBJ(1200)
    call thistype.SUMMON_UNIT_TYPE.SpellPower.Set(60)
    call thistype.SUMMON_UNIT_TYPE.Attack.Set(Attack.HOMING_MISSILE)
    call thistype.SUMMON_UNIT_TYPE.Attack.Range.Set(300)
    call thistype.SUMMON_UNIT_TYPE.Attack.Speed.SetByCooldown(0.5)
    call thistype.SUMMON_UNIT_TYPE.Damage.Delay.Set(0.1)
    call thistype.SUMMON_UNIT_TYPE.Attack.Missile.Speed.Set(600)
    call thistype.SUMMON_UNIT_TYPE.Damage.Set(2)
    call thistype.SUMMON_UNIT_TYPE.Damage.SetBJ(2)
    call thistype.SUMMON_UNIT_TYPE.Damage.Dices.Set(1)
    call thistype.SUMMON_UNIT_TYPE.Damage.Sides.Set(3)
    call thistype.SUMMON_UNIT_TYPE.Damage.Type.Set(Attack.DMG_TYPE_MAGIC)
    call thistype.SUMMON_UNIT_TYPE.CollisionSize.Set(25)
    call thistype.SUMMON_UNIT_TYPE.Abilities.Add(TorchLight(NULL).THIS_SPELL)
    call thistype.SUMMON_UNIT_TYPE.Abilities.Add(RevealAura(NULL).THIS_SPELL)
    call DebugEx("init " + "D:\\Warcraft III\\Maps\\DWC\\Scripts\\Misc\\Pharmacy.page\\Pharmacy.struct\\EyeOfTheFlame.page\\EyeOfTheFlame.struct\\summonUnitType.wc3unit")
    call t.Destroy()
endmethod