umswe.setarchive("umswe\\umswe.mpq")

 -- enable
if umscore then
	
	-- load required files
	umswe.registerini("UI\\WorldEditStrings.txt","westrings")
	umswe.registerini("UI\\WorldEditLayout.txt","welayout")
	umswe.registerini("UI\\MiscData.txt","miscdata")
	umswe.registerini("UI\\WorldEditData.txt","wedata")
	umswe.registerslk("Units\\UnitUI.slk","unitui")
	umswe.registerslk("Units\\AbilityData.slk","abildata")
	umswe.registerslk("Units\\UpgradeMetaData.slk","upmeta")
	umswe.registerslk("Units\\UpgradeEffectMetaData.slk","upeffectmeta")
	umswe.registerslk("Doodads\\DoodadMetaData.slk","doodmeta")
	umswe.registerslk("Units\\DestructableMetaData.slk","destmeta")
	umswe.registerslk("Units\\AbilityBuffMetaData.slk","abilmeta")
	umswe.registerslk("UI\\SkinMetaData.slk","skinmeta")
	umswe.registerslk("Units\\MiscMetaData.slk","miscmeta")
	umswe.registerslk("Units\\AbilityMetaData.slk","abilmeta")
	umswe.registerslk("Units\\UnitMetaData.slk","unitmeta")
	
	-- TEXT FILES
	
	-- ui world edit layout
	umswe.applyini(welayout,"VariableDialog","Dlg_Size","480,285")
	umswe.applyini(welayout,"AboutDialog","AppVersion_Size","400,16")
	
	-- ui misc data
	umswe.applyini(miscdata,"Terrain","MaxSlope","90") -- foor steep hills
	umswe.applyini(miscdata,"Terrain","MaxHeight","3712") -- extended limits
	umswe.applyini(miscdata,"Terrain","MinHeight","-2048")
	
	-- ui world edit data
	umswe.applyini(wedata,"WorldEditMisc","MaximumMapSize","480")
	umswe.applyini(wedata,"ExtraIcons","00","1,ReplaceableTextures\\CommandButtons\\BTNResStone.blp,WESTRING_DEST_RES_STONEB")
	umswe.applyini(wedata,"ExtraIcons","01","1,ReplaceableTextures\\CommandButtons\\BTNBarrel.blp,WESTRING_DEST_BARRELB")
	umswe.applyini(wedata,"ExtraIcons","02","1,ReplaceableTextures\\CommandButtons\\BTNOtherBarrel.blp,WESTRING_DEST_OTHERBARRELB")
	umswe.applyini(wedata,"ExtraIcons","03","1,ReplaceableTextures\\CommandButtons\\BTNBox.blp,WESTRING_DEST_BOXB")
	umswe.applyini(wedata,"ExtraIcons","04","1,ReplaceableTextures\\CommandButtons\\BTNCrate.blp,WESTRING_DOOD_LOCSB")
	umswe.applyini(wedata,"ExtraIcons","05","0,ReplaceableTextures\\WorldEditUI\\StartingLocation.blp,WESTRING_STARTLOCATIONB")
	umswe.applyini(wedata,"ExtraIcons","06","0,ReplaceableTextures\\WorldEditUI\\DoodadPlaceholder.blp,WESTRING_ICON_INVALIDB")
	umswe.applyini(wedata,"ExtraIcons","07","0,ReplaceableTextures\\WorldEditUI\\Editor-Random-Unit.blp,WESTRING_RANDOM_UNITB")
	umswe.applyini(wedata,"ExtraIcons","08","0,ReplaceableTextures\\WorldEditUI\\Editor-Random-Building.blp,WESTRING_RANDOM_BUILDINGB")
	umswe.applyini(wedata,"ExtraIcons","09","0,ReplaceableTextures\\WorldEditUI\\Editor-Random-Item.blp,WESTRING_RANDOM_ITEMB")
	umswe.applyini(wedata,"ExtraModels","00","0,Objects\\StartLocation\\StartLocation,WESTRING_MODEL_SLOC")
	
	-- more icons
	umswe.appendnrentry(wedata,"ExtraIcons","1,ReplaceableTextures\\CommandButtons\\BTNProudmoore.blp,WESTRING_HIDDENICON37")
	umswe.appendnrentry(wedata,"ExtraIcons","1,ReplaceableTextures\\CommandButtons\\BTNEngineeringUpgrade.blp,WESTRING_HIDDENICON38")
	umswe.appendnrentry(wedata,"ExtraIcons","1,ReplaceableTextures\\CommandButtons\\BTNLament.blp,WESTRING_HIDDENICON39")
	umswe.appendnrentry(wedata,"ExtraIcons","1,ReplaceableTextures\\CommandButtons\\BTNAuraOfDarkness.blp,WESTRING_HIDDENICON40")
	umswe.appendnrentry(wedata,"ExtraIcons","1,ReplaceableTextures\\CommandButtons\\BTNVengeanceIncarnate.tga,WESTRING_HIDDENICON41")
	umswe.appendnrentry(wedata,"ExtraIcons","1,ReplaceableTextures\\CommandButtons\\BTNillidanprisonwagon.tga,WESTRING_HIDDENICON42")
	umswe.appendnrentry(wedata,"ExtraIcons","1,ReplaceableTextures\\CommandButtons\\BTNEredarRed.blp,WESTRING_HIDDENICON43")
	umswe.appendnrentry(wedata,"ExtraIcons","1,ReplaceableTextures\\CommandButtons\\BTNHydra.blp,WESTRING_HIDDENICON44")
	umswe.appendnrentry(wedata,"ExtraIcons","1,ReplaceableTextures\\CommandButtons\\BTNillidanprisonwagon.tga,WESTRING_HIDDENICON45")
	umswe.appendnrentry(wedata,"ExtraIcons","1,ReplaceableTextures\\CommandButtons\\BTNDenOfWonders.tga,WESTRING_HIDDENICON46")
	umswe.appendnrentry(wedata,"ExtraIcons","1,ReplaceableTextures\\CommandButtons\\BTNAvengingAssassin.tga,WESTRING_HIDDENICON47")
	umswe.appendnrentry(wedata,"ExtraIcons","1,ReplaceableTextures\\CommandButtons\\BTNTuskaarNomad.tga,WESTRING_HIDDENICON48")
	umswe.appendnrentry(wedata,"ExtraIcons","1,ReplaceableTextures\\CommandButtons\\BTNRejuvenationPotion.blp,WESTRING_HIDDENICON49")
	umswe.appendnrentry(wedata,"ExtraIcons","1,ReplaceableTextures\\CommandButtons\\BTNQuillbeastGod.tga,WESTRING_HIDDENICON50")
	umswe.appendnrentry(wedata,"ExtraIcons","1,ReplaceableTextures\\CommandButtons\\BTNLamp.blp,WESTRING_HIDDENICON51")
	umswe.appendnrentry(wedata,"ExtraIcons","1,ReplaceableTextures\\CommandButtons\\BTNShoveler.blp,WESTRING_HIDDENICON52")
	umswe.appendnrentry(wedata,"ExtraIcons","1,ReplaceableTextures\\CommandButtons\\BTNManaShield.blp,WESTRING_HIDDENICON53")
	umswe.appendnrentry(wedata,"ExtraIcons","1,ReplaceableTextures\\CommandButtons\\BTNThornyShieldOff.blp,WESTRING_HIDDENICON54")
	umswe.appendnrentry(wedata,"ExtraIcons","1,ReplaceableTextures\\CommandButtons\\BTNFlamingArrows.blp,WESTRING_HIDDENICON55")
	umswe.appendnrentry(wedata,"ExtraIcons","1,ReplaceableTextures\\CommandButtons\\BTNPoisonArrow.blp,WESTRING_HIDDENICON56")
	umswe.appendnrentry(wedata,"ExtraIcons","1,ReplaceableTextures\\CommandButtons\\BTNRegeneration.blp,WESTRING_HIDDENICON57")
	umswe.appendnrentry(wedata,"ExtraIcons","1,ReplaceableTextures\\CommandButtons\\BTNBarkskin.blp,WESTRING_HIDDENICON58")
	umswe.appendnrentry(wedata,"ExtraIcons","1,ReplaceableTextures\\CommandButtons\\BTNBarkskinOn.blp,WESTRING_HIDDENICON59")
	umswe.appendnrentry(wedata,"ExtraIcons","1,ReplaceableTextures\\CommandButtons\\BTNBarkskinOff.blp,WESTRING_HIDDENICON60")
	umswe.appendnrentry(wedata,"ExtraIcons","1,ReplaceableTextures\\CommandButtons\\BTNBronzeBowl.blp,WESTRING_HIDDENICON61")
	umswe.appendnrentry(wedata,"ExtraIcons","1,ReplaceableTextures\\CommandButtons\\BTNBronzeBowlfull.blp,WESTRING_HIDDENICON62")
	umswe.appendnrentry(wedata,"ExtraIcons","1,ReplaceableTextures\\CommandButtons\\BTNChime.blp,WESTRING_HIDDENICON63")
	umswe.appendnrentry(wedata,"ExtraIcons","1,ReplaceableTextures\\CommandButtons\\BTNThievesGuild.blp,WESTRING_HIDDENICON64")
	umswe.appendnrentry(wedata,"ExtraIcons","1,ReplaceableTextures\\CommandButtons\\BTNMarine.blp,WESTRING_HIDDENICON65")
	umswe.appendnrentry(wedata,"ExtraIcons","1,ReplaceableTextures\\CommandButtons\\BTNPebble.blp,WESTRING_HIDDENICON66")
	umswe.appendnrentry(wedata,"ExtraIcons","1,ReplaceableTextures\\CommandButtons\\BTNAdvStruct.blp,WESTRING_HIDDENICON67")
	umswe.appendnrentry(wedata,"ExtraIcons","1,ReplaceableTextures\\CommandButtons\\BTNReplay-Play.blp,WESTRING_HIDDENICON68")
	umswe.appendnrentry(wedata,"ExtraIcons","1,ReplaceableTextures\\CommandButtons\\BTNReplay-Loop.blp,WESTRING_HIDDENICON69")
	umswe.appendnrentry(wedata,"ExtraIcons","1,ReplaceableTextures\\CommandButtons\\BTNReplay-Pause.blp,WESTRING_HIDDENICON70")
	umswe.appendnrentry(wedata,"ExtraIcons","1,ReplaceableTextures\\CommandButtons\\BTNReplay-Speedup.blp,WESTRING_HIDDENICON71")
	umswe.appendnrentry(wedata,"ExtraIcons","1,ReplaceableTextures\\CommandButtons\\BTNReplay-Speeddown.blp,WESTRING_HIDDENICON72")
	umswe.appendnrentry(wedata,"ExtraIcons","1,ReplaceableTextures\\CommandButtons\\BTNOrb.blp,WESTRING_HIDDENICON73")
	umswe.appendnrentry(wedata,"ExtraIcons","1,ReplaceableTextures\\CommandButtons\\BTNInn.blp,WESTRING_HIDDENICON74")
	umswe.appendnrentry(wedata,"ExtraIcons","1,ReplaceableTextures\\CommandButtons\\BTNPriestMaster.blp,WESTRING_HIDDENICON75")
	umswe.appendnrentry(wedata,"ExtraIcons","1,ReplaceableTextures\\CommandButtons\\BTNHeroMoonPriestess.blp,WESTRING_HIDDENICON76")
	umswe.appendnrentry(wedata,"ExtraIcons","1,ReplaceableTextures\\CommandButtons\\BTNSkillz.tga,WESTRING_HIDDENICON77")
	umswe.appendnrentry(wedata,"ExtraIcons","1,ReplaceableTextures\\CommandButtons\\BTNAkama.tga,WESTRING_HIDDENICON78")
	umswe.appendnrentry(wedata,"ExtraIcons","1,ReplaceableTextures\\CommandButtons\\BTNExpandedView.tga,WESTRING_HIDDENICON79")
	umswe.appendnrentry(wedata,"ExtraIcons","1,ReplaceableTextures\\CommandButtons\\BTNMGexchange.tga,WESTRING_HIDDENICON80")
	umswe.appendnrentry(wedata,"ExtraIcons","1,ReplaceableTextures\\CommandButtons\\BTNRepair.blp,WESTRING_HIDDENICON81")
	umswe.appendnrentry(wedata,"ExtraIcons","1,ReplaceableTextures\\CommandButtons\\BTNClusterRockets.blp,WESTRING_HIDDENICON82")
	umswe.appendnrentry(wedata,"ExtraIcons","1,ReplaceableTextures\\CommandButtons\\BTNReturnGoods.blp,WESTRING_HIDDENICON83")
	umswe.appendnrentry(wedata,"ExtraIcons","1,ReplaceableTextures\\CommandButtons\\BTNPatrol.blp,WESTRING_HIDDENICON84")
	umswe.appendnrentry(wedata,"ExtraIcons","1,ReplaceableTextures\\CommandButtons\\BTNAttackGround.blp,WESTRING_HIDDENICON85")
	umswe.appendnrentry(wedata,"ExtraIcons","1,ReplaceableTextures\\CommandButtons\\BTNStop.blp,WESTRING_HIDDENICON86")
	umswe.appendnrentry(wedata,"ExtraIcons","1,ReplaceableTextures\\CommandButtons\\BTNPickUpItem.blp,WESTRING_HIDDENICON87")
	umswe.appendnrentry(wedata,"ExtraIcons","1,ReplaceableTextures\\CommandButtons\\BTNWindWalkOff.blp,WESTRING_HIDDENICON88")
	umswe.appendnrentry(wedata,"ExtraIcons","1,ReplaceableTextures\\CommandButtons\\BTNGLExchange.blp,WESTRING_HIDDENICON89")
	umswe.appendnrentry(wedata,"ExtraIcons","1,ReplaceableTextures\\CommandButtons\\BTNOrcLumberUpgradeTwo.blp,WESTRING_HIDDENICON90")
	umswe.appendnrentry(wedata,"ExtraIcons","1,ReplaceableTextures\\CommandButtons\\BTNLGExchange.blp,WESTRING_HIDDENICON91")
	umswe.appendnrentry(wedata,"ExtraIcons","1,ReplaceableTextures\\CommandButtons\\BTNManual2.blp,WESTRING_HIDDENICON92")
	umswe.appendnrentry(wedata,"ExtraIcons","1,ReplaceableTextures\\CommandButtons\\BTNMove.blp,WESTRING_HIDDENICON93")
	umswe.appendnrentry(wedata,"ExtraIcons","1,ReplaceableTextures\\CommandButtons\\BTNAttack.blp,WESTRING_HIDDENICON94")
	umswe.appendnrentry(wedata,"ExtraIcons","1,ReplaceableTextures\\CommandButtons\\BTNHoldPosition.blp,WESTRING_HIDDENICON95")
	umswe.appendnrentry(wedata,"ExtraIcons","1,ReplaceableTextures\\CommandButtons\\BTNInvulnerable.blp,WESTRING_HIDDENICON96")
	umswe.appendnrentry(wedata,"ExtraIcons","1,ReplaceableTextures\\CommandButtons\\BTNSteamTank.blp,WESTRING_HIDDENICON97")
	umswe.appendnrentry(wedata,"ExtraIcons","1,ReplaceableTextures\\CommandButtons\\BTNWellSpring.blp,WESTRING_HIDDENICON98")
	umswe.appendnrentry(wedata,"ExtraIcons","1,ReplaceableTextures\\CommandButtons\\BTNSpellBreaker.blp,WESTRING_HIDDENICON99")
	umswe.appendnrentry(wedata,"ExtraIcons","1,ReplaceableTextures\\CommandButtons\\BTNShadowMeld.blp,WESTRING_HIDDENICON100")
	umswe.appendnrentry(wedata,"ExtraIcons","1,ReplaceableTextures\\CommandButtons\\BTNentanglemine.blp,WESTRING_HIDDENICON101")
	umswe.appendnrentry(wedata,"ExtraIcons","1,ReplaceableTextures\\CommandButtons\\BTNImprovedMining.blp,WESTRING_HIDDENICON102")
	umswe.appendnrentry(wedata,"ExtraIcons","1,ReplaceableTextures\\CommandButtons\\BTNMeatapult.blp,WESTRING_HIDDENICON103")
	umswe.appendnrentry(wedata,"ExtraIcons","1,ReplaceableTextures\\CommandButtons\\BTNSpiderling.blp,WESTRING_HIDDENICON104")
	umswe.appendnrentry(wedata,"ExtraIcons","1,ReplaceableTextures\\CommandButtons\\BTNDrain.blp,WESTRING_HIDDENICON105")
	umswe.appendnrentry(wedata,"ExtraIcons","1,ReplaceableTextures\\CommandButtons\\BTNUpgradeRegenerationAura.blp,WESTRING_HIDDENICON106")
	umswe.appendnrentry(wedata,"ExtraIcons","1,ReplaceableTextures\\CommandButtons\\BTNSell.blp,WESTRING_HIDDENICON107")
	umswe.appendnrentry(wedata,"ExtraIcons","1,ReplaceableTextures\\CommandButtons\\BTNDryadDispelMagic.blp,WESTRING_HIDDENICON108")
	umswe.appendnrentry(wedata,"ExtraIcons","1,ReplaceableTextures\\CommandButtons\\BTNUndeadLoad.blp,WESTRING_HIDDENICON109")
	umswe.appendnrentry(wedata,"ExtraIcons","1,ReplaceableTextures\\CommandButtons\\BTNDizzy.blp,WESTRING_HIDDENICON110")
	umswe.appendnrentry(wedata,"ExtraIcons","1,ReplaceableTextures\\CommandButtons\\BTNFrost.blp,WESTRING_HIDDENICON111")
	umswe.appendnrentry(wedata,"ExtraIcons","1,ReplaceableTextures\\CommandButtons\\BTNGuardianWard.blp,WESTRING_HIDDENICON112")
	umswe.appendnrentry(wedata,"ExtraIcons","1,ReplaceableTextures\\CommandButtons\\BTNMarketPlace.blp,WESTRING_HIDDENICON113")
	umswe.appendnrentry(wedata,"ExtraIcons","1,ReplaceableTextures\\CommandButtons\\BTNNaturesBlessing.blp,WESTRING_HIDDENICON114")
	umswe.appendnrentry(wedata,"ExtraIcons","1,ReplaceableTextures\\CommandButtons\\BTNPotionBlue.blp,WESTRING_HIDDENICON115")
	umswe.appendnrentry(wedata,"ExtraIcons","1,ReplaceableTextures\\CommandButtons\\BTNSpy.blp,WESTRING_HIDDENICON116")
	umswe.appendnrentry(wedata,"ExtraIcons","1,ReplaceableTextures\\CommandButtons\\BTNStun.blp,WESTRING_HIDDENICON117")
	umswe.appendnrentry(wedata,"ExtraIcons","1,ReplaceableTextures\\CommandButtons\\BTNWirtsLeg.blp,WESTRING_HIDDENICON118")
	umswe.appendnrentry(wedata,"ExtraIcons","1,ReplaceableTextures\\CommandButtons\\BTNWirtsOtherLeg.blp,WESTRING_HIDDENICON119")
	umswe.appendnrentry(wedata,"ExtraIcons","1,ReplaceableTextures\\CommandButtons\\BTNHealingSpray.blp,WESTRING_HIDDENICON120")
	umswe.appendnrentry(wedata,"ExtraIcons","1,ReplaceableTextures\\CommandButtons\\BTNTransmute.blp,WESTRING_HIDDENICON121")
	umswe.appendnrentry(wedata,"ExtraIcons","1,ReplaceableTextures\\CommandButtons\\BTNChemicalRage.blp,WESTRING_HIDDENICON122")
	umswe.appendnrentry(wedata,"ExtraIcons","1,ReplaceableTextures\\CommandButtons\\BTNAcidbomb.blp,WESTRING_HIDDENICON123")
	umswe.appendnrentry(wedata,"ExtraIcons","1,ReplaceableTextures\\CommandButtons\\BTNElunesBlessing.blp,WESTRING_HIDDENICON124")
	
	-- more models
	umswe.appendnrentry(wedata,"ExtraModels","1,Units\\Demon\\ChaosOrcRange\\ChaosOrcRange,WESTRING_HIDDENMODEL11")
	umswe.appendnrentry(wedata,"ExtraModels","1,Units\\Orc\\AncestralGuardian\\AncestralGuardian,WESTRING_HIDDENMODEL12")
	umswe.appendnrentry(wedata,"ExtraModels","1,Units\\Critters\\Frog\\Frog,WESTRING_HIDDENMODEL13")
	umswe.appendnrentry(wedata,"ExtraModels","1,Units\\Creeps\\BurningArcher\\BurningArcher,WESTRING_HIDDENMODEL14")
	umswe.appendnrentry(wedata,"ExtraModels","1,Buildings\\Undead\\GargoyleSpire\\GargoyleSpire,WESTRING_HIDDENMODEL15")
	umswe.appendnrentry(wedata,"ExtraModels","1,Units\\Other\\IllidanWagon\\IllidanWagon,WESTRING_HIDDENMODEL16")
	umswe.appendnrentry(wedata,"ExtraModels","1,Units\\critters\\Bloodelfpeasant\\BloodElfpeasant,WESTRING_HIDDENMODEL17")
	umswe.appendnrentry(wedata,"ExtraModels","1,Units\\Nightelf\\Nightelffishingboat\\Nightelffishingboat,WESTRING_HIDDENMODEL18")
	umswe.appendnrentry(wedata,"ExtraModels","1,SharedModels\\IllidanImprisoned,WESTRING_HIDDENMODEL19")
	umswe.appendnrentry(wedata,"ExtraModels","1,SharedModels\\EntangleWisp,WESTRING_HIDDENMODEL20")
	umswe.appendnrentry(wedata,"ExtraModels","1,Abilities\\Weapons\\BallsOfFireMissile\\BallsOfFireMissile,WESTRING_HIDDENMODEL21")
	umswe.appendnrentry(wedata,"ExtraModels","1,Abilities\\Weapons\\FlyingMachine\\FlyingMachineMissile,WESTRING_HIDDENMODEL22")
	umswe.appendnrentry(wedata,"ExtraModels","1,Abilities\\Weapons\\FragDriller\\FragDriller.md,WESTRING_HIDDENMODEL23")
	umswe.appendnrentry(wedata,"ExtraModels","1,Abilities\\Weapons\\RexxarMissile\\RexxarMissile,WESTRING_HIDDENMODEL24")
	umswe.appendnrentry(wedata,"ExtraModels","1,Abilities\\Weapons\\snapMissile\\snapMissile,WESTRING_HIDDENMODEL25")
	umswe.appendnrentry(wedata,"ExtraModels","1,Abilities\\Weapons\\SteamMissile\\SteamMissile,WESTRING_HIDDENMODEL26")
	umswe.appendnrentry(wedata,"ExtraModels","1,Abilities\\Weapons\\WingedSerpentMissile\\WingedSerpentMissile,WESTRING_HIDDENMODEL27")
	umswe.appendnrentry(wedata,"ExtraModels","1,Units\\Creeps\\StormPandarenBrewmaster\\StormPandarenBrewmaster_Missile,WESTRING_HIDDENMODEL28")
	umswe.appendnrentry(wedata,"ExtraModels","1,Units\\Creeps\\EarthPandarenBrewmaster\\EarthPandarenBrewmaster_Missile,WESTRING_HIDDENMODEL29")
	umswe.appendnrentry(wedata,"ExtraModels","1,Abilities\\Spells\\Human\\HolyBolt\\HolyBoltMissile,WESTRING_HIDDENMODEL30")
	umswe.appendnrentry(wedata,"ExtraModels","1,Abilities\\Weapons\\BallistaMissile\\BallistaMissile,WESTRING_HIDDENMODEL31")
	umswe.appendnrentry(wedata,"ExtraModels","1,Abilities\\Weapons\\FlamingArrow\\FlamingArrowMissile,WESTRING_HIDDENMODEL32")
	umswe.appendnrentry(wedata,"ExtraModels","1,Abilities\\Weapons\\MeatwagonMissile\\T_MeatwagonMissile,WESTRING_HIDDENMODEL33")
	umswe.appendnrentry(wedata,"ExtraModels","1,Abilities\\Weapons\\Mortar\\ScatterShotMissile,WESTRING_HIDDENMODEL34")
	umswe.appendnrentry(wedata,"ExtraModels","1,Abilities\\Weapons\\RangerMissile\\RangerMissile,WESTRING_HIDDENMODEL35")
	umswe.appendnrentry(wedata,"ExtraModels","1,Abilities\\Weapons\\TreantMissile\\TreantMissile,WESTRING_HIDDENMODEL36")
	umswe.appendnrentry(wedata,"ExtraModels","1,Abilities\\Spells\\Human\\FragmentationShards\\FragMissile,WESTRING_HIDDENMODEL37")
	umswe.appendnrentry(wedata,"ExtraModels","1,Abilities\\Spells\\Human\\MarkOfChaos\\MarkOfChaosDone,WESTRING_HIDDENMODEL38")
	umswe.appendnrentry(wedata,"ExtraModels","1,Abilities\\Spells\\Items\\ClarityPotion\\ClarityTarget,WESTRING_HIDDENMODEL39")
	umswe.appendnrentry(wedata,"ExtraModels","1,Abilities\\Spells\\Items\\ScrollOfRegeneration\\Scroll_Regen_Target,WESTRING_HIDDENMODEL40")
	umswe.appendnrentry(wedata,"ExtraModels","1,Abilities\\Spells\\Items\\ScrollOfRejuvenation\\ScrollManaHealth,WESTRING_HIDDENMODEL41")
	umswe.appendnrentry(wedata,"ExtraModels","1,Abilities\\Spells\\Items\\StaffOfPurification\\PurificationCaster,WESTRING_HIDDENMODEL42")
	umswe.appendnrentry(wedata,"ExtraModels","1,Abilities\\Spells\\Items\\StaffOfPurification\\PurificationTarget,WESTRING_HIDDENMODEL43")
	umswe.appendnrentry(wedata,"ExtraModels","1,Abilities\\Spells\\Other\\ForkedLightning\\ForkedLightningTarget,WESTRING_HIDDENMODEL44")
	umswe.appendnrentry(wedata,"ExtraModels","1,Abilities\\Spells\\NightElf\\MoonWell\\CorruptedMoonWellTarget,WESTRING_HIDDENMODEL45")
	umswe.appendnrentry(wedata,"ExtraModels","1,Abilities\\Spells\\NightElf\\Tranquility\\TranquilityTarget,WESTRING_HIDDENMODEL46")
	umswe.appendnrentry(wedata,"ExtraModels","1,Abilities\\Spells\\Orc\\Berserker\\Berserkertarget,WESTRING_HIDDENMODEL47")
	umswe.appendnrentry(wedata,"ExtraModels","1,Abilities\\Spells\\Orc\\Bloodlust\\BloodLustSpecial,WESTRING_HIDDENMODEL48")
	umswe.appendnrentry(wedata,"ExtraModels","1,Abilities\\Spells\\Orc\\CommandAura\\CommandAuraTarget,WESTRING_HIDDENMODEL49")
	umswe.appendnrentry(wedata,"ExtraModels","1,Abilities\\Spells\\Other\\ANsa\\ANsaTarget,WESTRING_HIDDENMODEL50")
	umswe.appendnrentry(wedata,"ExtraModels","1,Abilities\\Spells\\Other\\HealTarget2\\HealTarget2,WESTRING_HIDDENMODEL51")
	umswe.appendnrentry(wedata,"ExtraModels","1,Abilities\\Weapons\\BallistaMissile\\BallistaImpact,WESTRING_HIDDENMODEL52")
	umswe.appendnrentry(wedata,"ExtraModels","1,Abilities\\Weapons\\BallistaMissile\\BallistaMissileTarget,WESTRING_HIDDENMODEL53")
	umswe.appendnrentry(wedata,"ExtraModels","1,Abilities\\Weapons\\Blood\\BloodImpact,WESTRING_HIDDENMODEL54")
	umswe.appendnrentry(wedata,"ExtraModels","1,Abilities\\Weapons\\HydraliskImpact\\T_HydraliskImpact,WESTRING_HIDDENMODEL55")
	umswe.appendnrentry(wedata,"ExtraModels","1,Abilities\\Weapons\\Mortar\\ScatterShotTarget,WESTRING_HIDDENMODEL56")
	umswe.appendnrentry(wedata,"ExtraModels","1,Abilities\\Weapons\\PoisonSting\\Rings_Green,WESTRING_HIDDENMODEL57")
	umswe.appendnrentry(wedata,"ExtraModels","1,SharedModels\\NEBirth,WESTRING_HIDDENMODEL58")
	umswe.appendnrentry(wedata,"ExtraModels","1,SharedModels\\UBirth,WESTRING_HIDDENMODEL59")
	umswe.appendnrentry(wedata,"ExtraModels","1,SharedModels\\BuildingParticleBeam,WESTRING_HIDDENMODEL60")
	umswe.appendnrentry(wedata,"ExtraModels","1,SharedModels\\ObsidianFeather,WESTRING_HIDDENMODEL61")
	umswe.appendnrentry(wedata,"ExtraModels","1,SharedModels\\Rocks1,WESTRING_HIDDENMODEL62")
	umswe.appendnrentry(wedata,"ExtraModels","1,SharedModels\\Feather1,WESTRING_HIDDENMODEL63")
	umswe.appendnrentry(wedata,"ExtraModels","1,SharedModels\\Feather2,WESTRING_HIDDENMODEL64")
	umswe.appendnrentry(wedata,"ExtraModels","1,SharedModels\\FeatherPurple,WESTRING_HIDDENMODEL65")
	umswe.appendnrentry(wedata,"ExtraModels","1,SharedModels\\FeatherPurple1,WESTRING_HIDDENMODEL66")
	umswe.appendnrentry(wedata,"ExtraModels","1,SharedModels\\Glow1_red,WESTRING_HIDDENMODEL67")
	umswe.appendnrentry(wedata,"ExtraModels","1,SharedModels\\Gutz1,WESTRING_HIDDENMODEL68")
	umswe.appendnrentry(wedata,"ExtraModels","1,SharedModels\\leaves,WESTRING_HIDDENMODEL69")
	umswe.appendnrentry(wedata,"ExtraModels","1,SharedModels\\lightning2,WESTRING_HIDDENMODEL70")
	umswe.appendnrentry(wedata,"ExtraModels","1,SharedModels\\Smoke1_Green,WESTRING_HIDDENMODEL71")
	umswe.appendnrentry(wedata,"ExtraModels","1,Abilities\\Spells\\NightElf\\SpiritOfVengeance\\SpiritOfVengeanceOrbs2,WESTRING_HIDDENMODEL72")
	umswe.appendnrentry(wedata,"ExtraModels","1,Abilities\\Spells\\NightElf\\SpiritOfVengeance\\SpiritOfVengeanceOrbs3,WESTRING_HIDDENMODEL73")
	umswe.appendnrentry(wedata,"ExtraModels","1,Abilities\\Spells\\NightElf\\SpiritOfVengeance\\SpiritOfVengeanceOrbs4,WESTRING_HIDDENMODEL74")
	umswe.appendnrentry(wedata,"ExtraModels","1,Abilities\\Spells\\NightElf\\SpiritOfVengeance\\SpiritOfVengeanceOrbs5,WESTRING_HIDDENMODEL75")
	umswe.appendnrentry(wedata,"ExtraModels","1,Abilities\\Spells\\NightElf\\SpiritOfVengeance\\SpiritOfVengeanceOrbs6,WESTRING_HIDDENMODEL76")
	umswe.appendnrentry(wedata,"ExtraModels","1,Abilities\\Spells\\Undead\\ThornyShield\\ThornyShieldTargetChestMountLeft,WESTRING_HIDDENMODEL77")
	umswe.appendnrentry(wedata,"ExtraModels","1,Abilities\\Spells\\Undead\\ThornyShield\\ThornyShieldTargetChestMountRight,WESTRING_HIDDENMODEL78")
	umswe.appendnrentry(wedata,"ExtraModels","1,Abilities\\Spells\\Undead\\ThornyShield\\ThornyShieldTargetChestRight,WESTRING_HIDDENMODEL79")
	umswe.appendnrentry(wedata,"ExtraModels","1,Environment\\SmallBuildingFire\\SmallBuildingFire0,WESTRING_HIDDENMODEL80")
	umswe.appendnrentry(wedata,"ExtraModels","1,Environment\\SmallBuildingFire\\SmallBuildingFire1,WESTRING_HIDDENMODEL81")
	umswe.appendnrentry(wedata,"ExtraModels","1,Environment\\LargeBuildingFire\\LargeBuildingFire0,WESTRING_HIDDENMODEL82")
	umswe.appendnrentry(wedata,"ExtraModels","1,Environment\\NightelfBuildingFire\\ElfSmallBuildingFire0,WESTRING_HIDDENMODEL83")
	umswe.appendnrentry(wedata,"ExtraModels","1,Environment\\NightelfBuildingFire\\ElfSmallBuildingFire1,WESTRING_HIDDENMODEL84")
	umswe.appendnrentry(wedata,"ExtraModels","1,Environment\\NightelfBuildingFire\\ElfLargeBuildingFire0,WESTRING_HIDDENMODEL85")
	umswe.appendnrentry(wedata,"ExtraModels","1,Environment\\NightelfBuildingFire\\ElfLargeBuildingFire2,WESTRING_HIDDENMODEL86")
	umswe.appendnrentry(wedata,"ExtraModels","1,Environment\\UndeadBuildingFire\\UndeadSmallBuildingFire0,WESTRING_HIDDENMODEL87")
	umswe.appendnrentry(wedata,"ExtraModels","1,Environment\\UndeadBuildingFire\\UndeadSmallBuildingFire1,WESTRING_HIDDENMODEL88")
	umswe.appendnrentry(wedata,"ExtraModels","1,Environment\\UndeadBuildingFire\\UndeadLargeBuildingFire0,WESTRING_HIDDENMODEL89")
	umswe.appendnrentry(wedata,"ExtraModels","1,Environment\\UndeadBuildingFire\\UndeadLargeBuildingFire2,WESTRING_HIDDENMODEL90")
	umswe.appendnrentry(wedata,"ExtraModels","1,Abilities\\Spells\\Demon\\ReviveDemon\\ReviveDemon,WESTRING_HIDDENMODEL91")
	umswe.appendnrentry(wedata,"ExtraModels","1,Abilities\\Spells\\NightElf\\ReviveNightElf\\ReviveNightElf,WESTRING_HIDDENMODEL92")
	umswe.appendnrentry(wedata,"ExtraModels","1,Abilities\\Spells\\Orc\\ReviveOrc\\ReviveOrc,WESTRING_HIDDENMODEL93")
	umswe.appendnrentry(wedata,"ExtraModels","1,Abilities\\Spells\\Undead\\ReviveUndead\\ReviveUndead,WESTRING_HIDDENMODEL94")
	umswe.appendnrentry(wedata,"ExtraModels","1,Abilities\\Spells\\Orc\\TrollBerserk\\HeadhunterWEAPONSRight,WESTRING_HIDDENMODEL95")
	umswe.appendnrentry(wedata,"ExtraModels","1,Abilities\\Spells\\Human\\FlameStrike\\FlameStrike,WESTRING_HIDDENMODEL96")
	umswe.appendnrentry(wedata,"ExtraModels","1,Abilities\\Spells\\Human\\FlameStrike\\FlameStrike2,WESTRING_HIDDENMODEL97")
	umswe.appendnrentry(wedata,"ExtraModels","1,Abilities\\Spells\\Other\\BreathOfFire\\BreathOfFireTarget,WESTRING_HIDDENMODEL98")
	umswe.appendnrentry(wedata,"ExtraModels","1,Doodads\\Northrend\\Structures\\AncientZiggurat\\AncientZiggurat0,WESTRING_HIDDENMODEL99")
	umswe.appendnrentry(wedata,"ExtraModels","1,Doodads\\Northrend\\Structures\\AncientZiggurat\\AncientZiggurat1,WESTRING_HIDDENMODEL100")
	umswe.appendnrentry(wedata,"ExtraModels","1,Doodads\\Cityscape\\Structures\\Morecitybuilding\\MoreCitybuilding0,WESTRING_HIDDENMODEL101")
	umswe.appendnrentry(wedata,"ExtraModels","1,Doodads\\Cityscape\\Structures\\Morecitybuilding\\MoreCitybuilding1,WESTRING_HIDDENMODEL102")
	umswe.appendnrentry(wedata,"ExtraModels","1,Doodads\\Cityscape\\Structures\\Morecitybuilding\\MoreCitybuilding2,WESTRING_HIDDENMODEL103")
	umswe.appendnrentry(wedata,"ExtraModels","1,Doodads\\Cityscape\\Structures\\Morecitybuilding\\MoreCitybuilding3,WESTRING_HIDDENMODEL104")
	umswe.appendnrentry(wedata,"ExtraModels","1,Doodads\\Cityscape\\Structures\\Morecitybuilding\\MoreCitybuilding4,WESTRING_HIDDENMODEL105")
	umswe.appendnrentry(wedata,"ExtraModels","1,Doodads\\Ashenvale\\Props\\Totem\\Totem0,WESTRING_HIDDENMODEL106")
	umswe.appendnrentry(wedata,"ExtraModels","1,Doodads\\Ashenvale\\Props\\Totem\\Totem1,WESTRING_HIDDENMODEL107")
	umswe.appendnrentry(wedata,"ExtraModels","1,Doodads\\Ashenvale\\Props\\Totem\\Totem2,WESTRING_HIDDENMODEL108")
	umswe.appendnrentry(wedata,"ExtraModels","1,Doodads\\LordaeronSummer\\Props\\Signpost\\Signpost0,WESTRING_HIDDENMODEL109")
	umswe.appendnrentry(wedata,"ExtraModels","1,Doodads\\LordaeronSummer\\Plants\\GrassTuft\\GrassTuft0,WESTRING_HIDDENMODEL110")
	umswe.appendnrentry(wedata,"ExtraModels","1,Doodads\\LordaeronSummer\\Plants\\GrassTuft\\GrassTuft1,WESTRING_HIDDENMODEL111")
	umswe.appendnrentry(wedata,"ExtraModels","1,Doodads\\LordaeronSummer\\Plants\\GrassTuft\\GrassTuft2,WESTRING_HIDDENMODEL112")
	umswe.appendnrentry(wedata,"ExtraModels","1,Doodads\\LordaeronSummer\\Plants\\GrassTuft\\GrassTuft3,WESTRING_HIDDENMODEL113")
	umswe.appendnrentry(wedata,"ExtraModels","1,Doodads\\LordaeronSummer\\Structures\\CityBridgeSmall\\CityBridgeSmall,WESTRING_HIDDENMODEL114")
	umswe.appendnrentry(wedata,"ExtraModels","1,Doodads\\LordaeronSummer\\Structures\\LordaeronBridge\\LordaeronBridge,WESTRING_HIDDENMODEL115")
	umswe.appendnrentry(wedata,"ExtraModels","1,Doodads\\LordaeronSummer\\Structures\\BridgeLog\\BridgeLog,WESTRING_HIDDENMODEL116")
	umswe.appendnrentry(wedata,"ExtraModels","1,Doodads\\Terrain\\G_RockChunks\\G_RockChunks0,WESTRING_HIDDENMODEL117")
	umswe.appendnrentry(wedata,"ExtraModels","1,Doodads\\Terrain\\G_RockChunks\\G_RockChunks1,WESTRING_HIDDENMODEL118")
	umswe.appendnrentry(wedata,"ExtraModels","1,Doodads\\Terrain\\G_RockChunks\\G_RockChunks2,WESTRING_HIDDENMODEL119")
	umswe.appendnrentry(wedata,"ExtraModels","1,Doodads\\Terrain\\G_RockChunks\\G_RockChunks3,WESTRING_HIDDENMODEL120")
	umswe.appendnrentry(wedata,"ExtraModels","1,Doodads\\Terrain\\G_RockChunks\\G_RockChunks4,WESTRING_HIDDENMODEL121")
	umswe.appendnrentry(wedata,"ExtraModels","1,Doodads\\Terrain\\G_RockChunks\\G_RockChunks5,WESTRING_HIDDENMODEL122")
	
	-- window titles
	umswe.setstr(westrings,"WESTRING_MODULE_SCRIPTS","Trigger Editor")
	umswe.setstr(westrings,"WESTRING_OBJECTEDITOR","Object Editor")
	umswe.setstr(westrings,"WESTRING_APPNAME","Warcraft III World Editor UMS 5.0")
	umswe.setstr(westrings,"WESTRING_ABOUTTITLE","About Warcraft III World Editor UMS")
	umswe.setstr(westrings,"WESTRING_ABOUT_VERSION","UMSWE Version 5.0 / World Editor Version ")
	umswe.setstr(westrings,"WESTRING_WELCOMETITLE","Welcome to the Warcraft III World Editor UMS")
	umswe.setstr(westrings,"WESTRING_WELCOME_LARGETEXT","Welcome to the Warcraft III World Editor UMS")
	
	-- umswe logo
	umswe.applyini(wedata,"WorldEditArt","War3Logo","ReplaceableTextures\\WorldEditUI\\UMSWE")
	umswe.applyini(wedata,"WorldEditArt","War3XLogo","ReplaceableTextures\\WorldEditUI\\UMSWE")
	
	-- hidden icons and models
	umswe.prependstr(westrings,"WESTRING_MODEL_CHECKCUBE_1","Extra Model -")
	umswe.prependstr(westrings,"WESTRING_MODEL_CHECKCUBE_2","Extra Model -")
	umswe.prependstr(westrings,"WESTRING_MODEL_CAMERA","Extra Model -")
	umswe.prependstr(westrings,"WESTRING_MODEL_QUESTION","Extra Model -")
	umswe.prependstr(westrings,"WESTRING_MODEL_EXCLAMATION","Extra Model -")
	umswe.prependstr(westrings,"WESTRING_MODEL_MALFURIONNOSTAG","Extra Model -")
	umswe.prependstr(westrings,"WESTRING_MODEL_VICTORYCINEMATICARTHAS","Extra Model -")
	umswe.prependstr(westrings,"WESTRING_MODEL_VICTORYCINEMATICILLIDAN","Extra Model -")
	umswe.prependstr(westrings,"WESTRING_MODEL_RUNE","Extra Model -")
	umswe.prependstr(westrings,"WESTRING_ICON_INVALID","Extra Icon -")
	umswe.prependstr(westrings,"WESTRING_ICON_MINIMAP_GOLD","Extra Icon -")
	umswe.prependstr(westrings,"WESTRING_ICON_MINIMAP_BUILDING","Extra Icon -")
	umswe.prependstr(westrings,"WESTRING_ICON_MINIMAP_STARTLOC","Extra Icon -")
	umswe.prependstr(westrings,"WESTRING_ICON_MINIMAP_CREEPS1","Extra Icon -")
	umswe.prependstr(westrings,"WESTRING_ICON_MINIMAP_CREEPS2","Extra Icon -")
	umswe.prependstr(westrings,"WESTRING_ICON_MULTIPLE_UNITS","Extra Icon -")
	umswe.prependstr(westrings,"WESTRING_ICON_MULTIPLE_DOODADS","Extra Icon -")
	umswe.prependstr(westrings,"WESTRING_ICON_FORCE","Extra Icon -")
	umswe.prependstr(westrings,"WESTRING_ICON_ITEMSET","Extra Icon -")
	umswe.prependstr(westrings,"WESTRING_ICON_ALLY_HIGH","Extra Icon -")
	umswe.prependstr(westrings,"WESTRING_ICON_ALLY_LOW","Extra Icon -")
	umswe.prependstr(westrings,"WESTRING_ICON_ALLY_NONE","Extra Icon -")
	umswe.prependstr(westrings,"WESTRING_ICON_DOODCAT_PROPS","Extra Icon -")
	umswe.prependstr(westrings,"WESTRING_ICON_DOODCAT_STRUCT","Extra Icon -")
	umswe.prependstr(westrings,"WESTRING_ICON_DOODCAT_WATER","Extra Icon -")
	umswe.prependstr(westrings,"WESTRING_ICON_DOODCAT_CLIFF","Extra Icon -")
	umswe.prependstr(westrings,"WESTRING_ICON_DOODCAT_ENV","Extra Icon -")
	umswe.prependstr(westrings,"WESTRING_ICON_DOODCAT_CINEMA","Extra Icon -")
	umswe.prependstr(westrings,"WESTRING_ICON_DOODCAT_DEST","Extra Icon -")
	umswe.prependstr(westrings,"WESTRING_ICON_DOODCAT_BRIDGE","Extra Icon -")
	umswe.prependstr(westrings,"WESTRING_ICON_DWARFIN","Hidden Icon -")
	umswe.prependstr(westrings,"WESTRING_ICON_DWARFOUT","Hidden Icon -")
	umswe.prependstr(westrings,"WESTRING_ICON_ACORN","Hidden Icon -")
	umswe.prependstr(westrings,"WESTRING_ICON_MINIMAPENTRANCE","Extra Icon -")
	umswe.prependstr(westrings,"WESTRING_ICON_MINIMAPENTRANCESMALL","Extra Icon -")
	umswe.prependstr(westrings,"WESTRING_ICON_SCORESCREEN_NAGA","Extra Icon -")
	umswe.prependstr(westrings,"WESTRING_ICON_SCORESCREEN_BLOODELF","Extra Icon -")
	
	-- spirit link fix
	umswe.setstr(westrings,"WESTRING_AEVAL_SPL1","Main Target Damage Factor")
	
	-- operator fixes
	umswe.appendstr(westrings,"WESTRING_COMPARISONOPERATOR_EQUAL","(==)")
	umswe.appendstr(westrings,"WESTRING_COMPARISONOPERATOR_NOTEQUAL","(!=)")
	umswe.appendstr(westrings,"WESTRING_COMPARISONOPERATOR_GREATER","(>)")
	umswe.appendstr(westrings,"WESTRING_COMPARISONOPERATOR_GREATEREQ","(>=)")
	umswe.appendstr(westrings,"WESTRING_COMPARISONOPERATOR_LESS","(<)")
	umswe.appendstr(westrings,"WESTRING_COMPARISONOPERATOR_LESSEQ","(<=)")
	umswe.appendstr(westrings,"WESTRING_EQUALNOTEQUALOPERATOR_EQUAL","(==)")
	umswe.appendstr(westrings,"WESTRING_EQUALNOTEQUALOPERATOR_NOTEQUAL","(!=)")
	
	-- preset values in brackets
	umswe.appendstr(westrings,"WESTRING_QUEUE_DELAY_QUEST","(5.00)")
	umswe.appendstr(westrings,"WESTRING_QUEUE_DELAY_HINT","(5.00)")
	umswe.appendstr(westrings,"WESTRING_QUEUE_DELAY_SECRET","(3.00)")
	umswe.appendstr(westrings,"WESTRING_HANDICAP_EASY","(60.00)")
	umswe.appendstr(westrings,"WESTRING_REAL_CELLWIDTH","(128.0)")
	umswe.appendstr(westrings,"WESTRING_REAL_UNITFACING","(270.0)")
	umswe.appendstr(westrings,"WESTRING_CAMDEFAULT_DISTANCE","(1650)")
	umswe.appendstr(westrings,"WESTRING_CAMDEFAULT_FARZ","(5000)")
	umswe.appendstr(westrings,"WESTRING_CAMDEFAULT_AOA","(304)")
	umswe.appendstr(westrings,"WESTRING_CAMDEFAULT_FOV","(70)")
	umswe.appendstr(westrings,"WESTRING_CAMDEFAULT_ROLL","(0)")
	umswe.appendstr(westrings,"WESTRING_CAMDEFAULT_ROTATION","(90)")
	umswe.appendstr(westrings,"WESTRING_REAL_E","(2.71828)")
	umswe.appendstr(westrings,"WESTRING_REAL_PI","(3.14159)")
	
	-- type fixes
	umswe.appendstr(westrings,"WESTRING_TRIGTYPE_abilcode","(abilcode)")
	umswe.appendstr(westrings,"WESTRING_TRIGTYPE_boolean","(boolean)")
	umswe.appendstr(westrings,"WESTRING_TRIGTYPE_buffcode","(buff)")
	umswe.appendstr(westrings,"WESTRING_TRIGTYPE_boolean","(boolean)")
	umswe.appendstr(westrings,"WESTRING_TRIGTYPE_camerasetup","(camerasetup)")
	umswe.appendstr(westrings,"WESTRING_TRIGTYPE_destructable","(destructable)")
	umswe.appendstr(westrings,"WESTRING_TRIGTYPE_destructablecode","(destructablecode)")
	umswe.appendstr(westrings,"WESTRING_TRIGTYPE_defeatcondition","(defeatcondition)")
	umswe.appendstr(westrings,"WESTRING_TRIGTYPE_dialog","(dialog)")
	umswe.appendstr(westrings,"WESTRING_TRIGTYPE_button","(button)")
	umswe.appendstr(westrings,"WESTRING_TRIGTYPE_texttag","(texttag)")
	umswe.appendstr(westrings,"WESTRING_TRIGTYPE_gamecache","(gamecache)")
	umswe.appendstr(westrings,"WESTRING_TRIGTYPE_gamespeed","(gamespeed)")
	umswe.appendstr(westrings,"WESTRING_TRIGTYPE_integer","(integer)")
	umswe.appendstr(westrings,"WESTRING_TRIGTYPE_item","(item)")
	umswe.appendstr(westrings,"WESTRING_TRIGTYPE_itemcode","(itemcode)")
	umswe.appendstr(westrings,"WESTRING_TRIGTYPE_itemtype","(itemtype)")
	umswe.appendstr(westrings,"WESTRING_TRIGTYPE_leaderboard","(leaderboard)")
	umswe.appendstr(westrings,"WESTRING_TRIGTYPE_multiboard","(multiboard)")
	umswe.appendstr(westrings,"WESTRING_TRIGTYPE_ordercode","(ordercode)")
	umswe.appendstr(westrings,"WESTRING_TRIGTYPE_player","(player)")
	umswe.appendstr(westrings,"WESTRING_TRIGTYPE_playercolor","(playercolor)")
	umswe.appendstr(westrings,"WESTRING_TRIGTYPE_force","(force)")
	umswe.appendstr(westrings,"WESTRING_TRIGTYPE_location","(location)")
	umswe.appendstr(westrings,"WESTRING_TRIGTYPE_quest","(quest)")
	umswe.appendstr(westrings,"WESTRING_TRIGTYPE_questitem","(questitem)")
	umswe.appendstr(westrings,"WESTRING_TRIGTYPE_race","(race)")
	umswe.appendstr(westrings,"WESTRING_TRIGTYPE_real","(real)")
	umswe.appendfixedstr(westrings,"WESTRING_TRIGTYPE_rect","(rect)","region","rect")
	umswe.appendstr(westrings,"WESTRING_TRIGTYPE_sound","(sound)")
	umswe.appendstr(westrings,"WESTRING_TRIGTYPE_effect","(effect)")
	umswe.appendstr(westrings,"WESTRING_TRIGTYPE_string","(string)")
	umswe.appendstr(westrings,"WESTRING_TRIGTYPE_techcode","(techcode)")
	umswe.appendstr(westrings,"WESTRING_TRIGTYPE_timer","(timer)")
	umswe.appendstr(westrings,"WESTRING_TRIGTYPE_timerdialog","(timerdialog)")
	umswe.appendstr(westrings,"WESTRING_TRIGTYPE_trigger","(trigger)")
	umswe.appendstr(westrings,"WESTRING_TRIGTYPE_unit","(unit)")
	umswe.appendstr(westrings,"ESTRING_TRIGTYPE_group","(group)")
	umswe.appendstr(westrings,"WESTRING_TRIGTYPE_unitcode","(unitcode)")
	umswe.appendstr(westrings,"WESTRING_TRIGTYPE_fogmodifier","(fogmodifier)")
	umswe.appendstr(westrings,"WESTRING_TRIGTYPE_weathereffect","(weathereffect)")
	umswe.appendstr(westrings,"WESTRING_TRIGTYPE_terraindeformation","(terraindeformation)")
	umswe.appendstr(westrings,"WESTRING_TRIGTYPE_code","(code)")
	umswe.appendstr(westrings,"WESTRING_TRIGTYPE_event","(event)")
	umswe.appendstr(westrings,"WESTRING_TRIGTYPE_triggeraction","(triggeraction)")
	umswe.appendstr(westrings,"WESTRING_TRIGTYPE_triggercondition","(triggercondition)")
	umswe.appendstr(westrings,"WESTRING_TRIGTYPE_boolexpr","(boolexpr)")
	umswe.appendstr(westrings,"WESTRING_COD_TYPE_ATTACKTYPE","(attacktype)")
	umswe.appendstr(westrings,"WESTRING_TRIGTYPE_damagetype","(damagetype)")
	umswe.appendstr(westrings,"WESTRING_TRIGTYPE_lightning","(lightning)")
	umswe.appendstr(westrings,"WESTRING_COD_TYPE_COMBATSOUND","(weapontype)")
	umswe.appendstr(westrings,"WESTRING_TRIGTYPE_effecttype","(effecttype)")
	umswe.appendstr(westrings,"WESTRING_TRIGTYPE_soundtype","(soundtype)")
	umswe.appendstr(westrings,"WESTRING_TRIGTYPE_image","(image)")
	umswe.appendstr(westrings,"WESTRING_TRIGTYPE_ubersplat","(ubersplat)")
	umswe.appendstr(westrings,"WESTRING_TRIGTYPE_pathingtype","(pathingtype)")
	umswe.appendstr(westrings,"WESTRING_TRIGTYPE_lightningtype","(string)")
	umswe.appendstr(westrings,"WESTRING_TRIGTYPE_heroskillcode","(heroskillcode)")
	
	-- rect fixes
	umswe.fixstr(westrings,"WESTRING_TRIGCAT_REGION","region","rect")
	umswe.fixstr(westrings,"WESTRING_REGION","region","rect")
	umswe.fixstr(westrings,"WESTRING_REGIONS","region","rect")
	umswe.fixstr(westrings,"WESTRING_ENTERREGIONNAME","region","rect")
	umswe.fixstr(westrings,"WESTRING_SELECTOBJ_REGION","region","rect")
	umswe.fixstr(westrings,"WESTRING_OBJTYPE_REGION","region","rect")
	umswe.fixstr(westrings,"WESTRING_MINIMAPOPT_REGIONS","region","rect")
	umswe.fixstr(westrings,"WESTRING_UPROPS_NOREGIONS","region","rect")
	umswe.fixstr(westrings,"WESTRING_OM_VIEW_REGIONS","region","rect")
	umswe.fixstr(westrings,"WESTRING_OM_MSROW_REGIONS","region","rect")
	umswe.fixstr(westrings,"WESTRING_REGIONPROPS","region","rect")
	umswe.fixstr(westrings,"WESTRING_REGIONPROPS_MULTIPLE","region","rect")
	umswe.fixstr(westrings,"WESTRING_REGION_CM_EDITPROPS","region","rect")
	umswe.fixstr(westrings,"WESTRING_REGION_CM_VIEW","region","rect")
	umswe.fixstr(westrings,"WESTRING_REGION_CM_RENAME","region","rect")
	umswe.fixstr(westrings,"WESTRING_REGION_CM_DELETE","region","rect")
	umswe.fixstr(westrings,"WESTRING_PALETTE_REGIONS","region","rect")
	umswe.fixstr(westrings,"WESTRING_LOADING_REGIONS","region","rect")
	umswe.fixstr(westrings,"WESTRING_SAVING_REGIONS","region","rect")
	umswe.fixstr(westrings,"WESTRING_SAVING_MAPSCRIPT_REGIONS","region","rect")
	umswe.fixstr(westrings,"WESTRING_UNDO_ADD_REGION","region","rect")
	umswe.fixstr(westrings,"WESTRING_UNDO_DELETE_REGION","region","rect")
	umswe.fixstr(westrings,"WESTRING_UNDO_PASTE_REGION","region","rect")
	umswe.fixstr(westrings,"WESTRING_UNDO_MODIFY_REGION","region","rect")
	umswe.fixstr(westrings,"WESTRING_WARNING_REGIONEXISTS","region","rect")
	umswe.fixstr(westrings,"WESTRING_WARNING_REGIONNAMEALLSPACES","region","rect")
	umswe.fixstr(westrings,"WESTRING_WARNING_REGIONUSEDBYUNITS1","region","rect")
	umswe.fixstr(westrings,"WESTRING_WARNING_REGIONUSEDBYUNITS2","region","rect")
	umswe.fixstr(westrings,"WESTRING_WARNING_SOUNDUSEDBYREGIONS1","region","rect")
	umswe.fixstr(westrings,"WESTRING_WARNING_SOUNDUSEDBYREGIONS2","region","rect")
	umswe.fixstr(westrings,"WESTRING_MENU_REGIONS","region","rect")
	umswe.fixstr(westrings,"WESTRING_MENU_OM_REGIONS","region","rect")
	
	umswe.appendini(westrings,"umswe\\WorldEditStringsAddon.txt") -- add all the missing strings
	
	-- SLK FILES
	
	-- unit ui
	umswe.applyall(unitui,"inEditor","1") -- enable all hidden units
	umswe.applyall(unitui,"hiddenInEditor","0")
	-- umswe.applyall(unitui"special","0") -- reorganize sorting
	
	-- ability data																							
	umswe.applyall(abildata,"useInEditor","1") -- show all hidden abilities
	
	-- upgrade meta data
	umswe.applyslk(upmeta,"glvl","maxVal","99999") -- allow for higher values
	umswe.applyslk(upmeta,"gglb","maxVal","999999")
	umswe.applyslk(upmeta,"gglm","maxVal","999999")
	umswe.applyslk(upmeta,"glmb","maxVal","999999")
	umswe.applyslk(upmeta,"glmm","maxVal","999999")
	umswe.applyslk(upmeta,"gtib","maxVal","999999")
	umswe.applyslk(upmeta,"gtim","maxVal","999999")
	
	-- upgrade effect meta data
	umswe.applyslk(upeffectmeta,"levb","minVal","-12960") -- allow for negative upgrades
	umswe.applyslk(upeffectmeta,"levm","minVal","-12960")
	umswe.applyslk(upeffectmeta,"mvxb","minVal","-99999")
	umswe.applyslk(upeffectmeta,"mvxm","minVal","-99999")
	umswe.applyslk(upeffectmeta,"atsb","minVal","-12960")
	umswe.applyslk(upeffectmeta,"atsm","minVal","-12960")
	umswe.applyslk(upeffectmeta,"sigb","minVal","-99999")
	umswe.applyslk(upeffectmeta,"sigm","minVal","-99999")
	umswe.applyslk(upeffectmeta,"levb","maxVal","12960")
	umswe.applyslk(upeffectmeta,"levm","maxVal","12960")
	umswe.applyslk(upeffectmeta,"mvxb","maxVal","99999")
	umswe.applyslk(upeffectmeta,"mvxm","maxVal","99999")
	umswe.applyslk(upeffectmeta,"atsb","maxVal","12960")
	umswe.applyslk(upeffectmeta,"atsm","maxVal","12960")
	umswe.applyslk(upeffectmeta,"sigb","maxVal","99999")
	umswe.applyslk(upeffectmeta,"sigm","maxVal","99999")
	
	-- doodad meta data
	umswe.applyslk(doodmeta,"ddes","minVal","0.000001") -- scale fixes
	umswe.applyslk(doodmeta,"dmis","minVal","0.000001")
	umswe.applyslk(doodmeta,"dmas","minVal","0.000001")
	
	-- destructable meta data
	umswe.applyslk(destmeta,"bmis","minVal","0.000001") -- scale fixes
	umswe.applyslk(destmeta,"bmas","minVal","0.000001")
	
	-- ability buff meta data
	umswe.applyslk(buffmeta,"fmsp","maxVal","65536") -- missilespeed fix
	
	-- skin meta data
	umswe.appendslk(skinmeta,"umswe\\SkinMetaDataAddon.slk") -- add some missing rows
	
	-- misc meta data
	umswe.applyslk(miscmeta,"guam","maxVal","999999") -- guard distance fix
	umswe.applyslk(miscmeta,"guad","maxVal","999999")
	umswe.applyslk(miscmeta,"guat","maxVal","999999")
	umswe.applyslk(miscmeta,"mxus","minVal","0")
	umswe.applyslk(miscmeta,"mnus","minVal","0")
	umswe.applyslk(miscmeta,"mxbs","minVal","0")
	umswe.applyslk(miscmeta,"mnbs","minVal","0")
	umswe.applyslk(miscmeta,"mxus","maxVal","65536")
	umswe.applyslk(miscmeta,"mnus","maxVal","65536")
	umswe.applyslk(miscmeta,"mxbs","maxVal","65536")
	umswe.applyslk(miscmeta,"mnbs","maxVal","65536")
	umswe.applyslk(miscmeta,"cccr","maxVal","65536")
	
	-- ability meta data
	umswe.applyslk(abilmeta,"Nic1","useSpecific","ANic,ANia") -- incinerate arrow fixes
	umswe.applyslk(abilmeta,"Nic2","useSpecific","ANic,ANia")
	umswe.applyslk(abilmeta,"Nic3","useSpecific","ANic,ANia")
	umswe.applyslk(abilmeta,"Nic4","useSpecific","ANic,ANia")
	umswe.applyslk(abilmeta,"Nic5","useSpecific","ANic,ANia")
	umswe.applyslk(abilmeta,"Nic6","useSpecific","ANic,ANia")
	umswe.applyslk(abilmeta,"Nvcu","type","string") -- volcano destructable id fix
	-- minVal
	umswe.applyslk(abilmeta,"Hbz1","minVal","0")
	umswe.applyslk(abilmeta,"Hbz2","minVal","0")
	umswe.applyslk(abilmeta,"Hbz3","minVal","0")
	umswe.applyslk(abilmeta,"Hmt1","minVal","0")
	umswe.applyslk(abilmeta,"Hwe2","minVal","0")
	umswe.applyslk(abilmeta,"Omi1","minVal","0")
	umswe.applyslk(abilmeta,"Uan1","minVal","0")
	umswe.applyslk(abilmeta,"Uan3","minVal","0")
	umswe.applyslk(abilmeta,"Udc1","minVal","0")
	umswe.applyslk(abilmeta,"Ocl2","minVal","0")
	umswe.applyslk(abilmeta,"Osf2","minVal","0")
	umswe.applyslk(abilmeta,"Efn1","minVal","0")
	umswe.applyslk(abilmeta,"Hre1","minVal","0")
	umswe.applyslk(abilmeta,"Ndp2","minVal","0")
	umswe.applyslk(abilmeta,"Ndp3","minVal","0")
	umswe.applyslk(abilmeta,"Nrc2","minVal","0")
	umswe.applyslk(abilmeta,"Apl3","minVal","-99999")
	umswe.applyslk(abilmeta,"Bgm3","minVal","0")
	umswe.applyslk(abilmeta,"Gld3","minVal","0")
	umswe.applyslk(abilmeta,"Gyd1","minVal","0")
	umswe.applyslk(abilmeta,"Har1","minVal","0")
	umswe.applyslk(abilmeta,"Mbt4","minVal","-99999")
	umswe.applyslk(abilmeta,"irc2","minVal","0")
	-- maxVal
	umswe.applyslk(abilmeta,"amsp","maxVal","65536")
	umswe.applyslk(abilmeta,"alev","maxVal","65536")
	umswe.applyslk(abilmeta,"arlv","maxVal","65536")
	umswe.applyslk(abilmeta,"alsk","maxVal","65536")
	umswe.applyslk(abilmeta,"acas","maxVal","65536")
	umswe.applyslk(abilmeta,"adur","maxVal","65536")
	umswe.applyslk(abilmeta,"ahdu","maxVal","65536")
	umswe.applyslk(abilmeta,"acdn","maxVal","65536")
	umswe.applyslk(abilmeta,"amcs","maxVal","65536")
	umswe.applyslk(abilmeta,"Omi1","maxVal","10")
	umswe.applyslk(abilmeta,"Apl3","maxVal","99999")
	umswe.applyslk(abilmeta,"Gld3","maxVal","99999")
	umswe.applyslk(abilmeta,"Gyd1","maxVal","32")
	umswe.applyslk(abilmeta,"Ihid","maxVal","99999")
	
	-- unit meta data
	-- minVal
	umswe.applyslk(unitmeta,"isca","minVal","0.000001")
	umswe.applyslk(unitmeta,"uagi","minVal","0")
	umswe.applyslk(unitmeta,"uint","minVal","0")
	umswe.applyslk(unitmeta,"ustr","minVal","0")
	umswe.applyslk(unitmeta,"umvf","minVal","-99999")
	umswe.applyslk(unitmeta,"umvh","minVal","-99999")
	umswe.applyslk(unitmeta,"usca","minVal","0.000001")
	umswe.applyslk(unitmeta,"ussc","minVal","0.000001")
	-- maxVal
	umswe.applyslk(unitmeta,"igol","maxVal","999999")
	umswe.applyslk(unitmeta,"ihtp","maxVal","999999")
	umswe.applyslk(unitmeta,"ilum","maxVal","999999")
	umswe.applyslk(unitmeta,"isca","maxVal","99999")
	umswe.applyslk(unitmeta,"isto","maxVal","99999")
	umswe.applyslk(unitmeta,"istr","maxVal","99999")
	umswe.applyslk(unitmeta,"isst","maxVal","99999")
	umswe.applyslk(unitmeta,"iuse","maxVal","99999")
	umswe.applyslk(unitmeta,"ua1z","maxVal","99999")
	umswe.applyslk(unitmeta,"ua2z","maxVal","99999")
	umswe.applyslk(unitmeta,"uagi","maxVal","99999")
	umswe.applyslk(unitmeta,"uagp","maxVal","99999")
	umswe.applyslk(unitmeta,"ubdi","maxVal","99999")
	umswe.applyslk(unitmeta,"ubba","maxVal","99999")
	umswe.applyslk(unitmeta,"ubsi","maxVal","99999")
	umswe.applyslk(unitmeta,"ulbd","maxVal","99999")
	umswe.applyslk(unitmeta,"ulba","maxVal","99999")
	umswe.applyslk(unitmeta,"ulbs","maxVal","99999")
	umswe.applyslk(unitmeta,"ucol","maxVal","99999")
	umswe.applyslk(unitmeta,"udef","maxVal","99999")
	umswe.applyslk(unitmeta,"udup","maxVal","99999")
	umswe.applyslk(unitmeta,"ugol","maxVal","999999")
	umswe.applyslk(unitmeta,"ugor","maxVal","999999")
	umswe.applyslk(unitmeta,"uhpm","maxVal","999999")
	umswe.applyslk(unitmeta,"uint","maxVal","99999")
	umswe.applyslk(unitmeta,"uinp","maxVal","99999")
	umswe.applyslk(unitmeta,"ulum","maxVal","999999")
	umswe.applyslk(unitmeta,"ulur","maxVal","999999")
	umswe.applyslk(unitmeta,"umpi","maxVal","999999")
	umswe.applyslk(unitmeta,"umpm","maxVal","999999")
	umswe.applyslk(unitmeta,"usin","maxVal","99999")
	umswe.applyslk(unitmeta,"uhpr","maxVal","99999")
	umswe.applyslk(unitmeta,"umpr","maxVal","99999")
	umswe.applyslk(unitmeta,"urtm","maxVal","99999")
	umswe.applyslk(unitmeta,"urpg","maxVal","99999")
	umswe.applyslk(unitmeta,"urpp","maxVal","99999")
	umswe.applyslk(unitmeta,"urpr","maxVal","99999")
	umswe.applyslk(unitmeta,"usid","maxVal","99999")
	umswe.applyslk(unitmeta,"umvs","maxVal","65536")
	umswe.applyslk(unitmeta,"usma","maxVal","99999")
	umswe.applyslk(unitmeta,"usrg","maxVal","99999")
	umswe.applyslk(unitmeta,"usst","maxVal","99999")
	umswe.applyslk(unitmeta,"ustr","maxVal","99999")
	umswe.applyslk(unitmeta,"ustp","maxVal","99999")
	umswe.applyslk(unitmeta,"uabr","maxVal","99999")
	umswe.applyslk(unitmeta,"umvf","maxVal","99999")
	umswe.applyslk(unitmeta,"umvh","maxVal","99999")
	umswe.applyslk(unitmeta,"upoi","maxVal","999999")
	umswe.applyslk(unitmeta,"upaw","maxVal","999999")
	umswe.applyslk(unitmeta,"uerd","maxVal","999999")
	umswe.applyslk(unitmeta,"ufrd","maxVal","999999")
	umswe.applyslk(unitmeta,"usca","maxVal","99999")
	umswe.applyslk(unitmeta,"uocc","maxVal","99999")
	umswe.applyslk(unitmeta,"urun","maxVal","99999")
	umswe.applyslk(unitmeta,"ussc","maxVal","99999")
	umswe.applyslk(unitmeta,"uslz","maxVal","99999")
	umswe.applyslk(unitmeta,"ushh","maxVal","99999")
	umswe.applyslk(unitmeta,"ushw","maxVal","99999")
	umswe.applyslk(unitmeta,"ushx","maxVal","99999")
	umswe.applyslk(unitmeta,"ushy","maxVal","99999")
	umswe.applyslk(unitmeta,"uwal","maxVal","99999")
	umswe.applyslk(unitmeta,"uacq","maxVal","99999")
	umswe.applyslk(unitmeta,"ua1c","maxVal","99999")
	umswe.applyslk(unitmeta,"ua2c","maxVal","99999")
	umswe.applyslk(unitmeta,"udl1","maxVal","99999")
	umswe.applyslk(unitmeta,"udl2","maxVal","99999")
	umswe.applyslk(unitmeta,"ua1d","maxVal","99999")
	umswe.applyslk(unitmeta,"ua2d","maxVal","99999")
	umswe.applyslk(unitmeta,"ua1b","maxVal","99999")
	umswe.applyslk(unitmeta,"ua2b","maxVal","99999")
	umswe.applyslk(unitmeta,"udu1","maxVal","99999")
	umswe.applyslk(unitmeta,"udu2","maxVal","99999")
	umswe.applyslk(unitmeta,"ua1f","maxVal","99999")
	umswe.applyslk(unitmeta,"ua2f","maxVal","99999")
	umswe.applyslk(unitmeta,"ua1h","maxVal","99999")
	umswe.applyslk(unitmeta,"ua2h","maxVal","99999")
	umswe.applyslk(unitmeta,"uamn","maxVal","99999")
	umswe.applyslk(unitmeta,"ua1q","maxVal","99999")
	umswe.applyslk(unitmeta,"ua2q","maxVal","99999")
	umswe.applyslk(unitmeta,"ua1r","maxVal","99999")
	umswe.applyslk(unitmeta,"ua2r","maxVal","99999")
	umswe.applyslk(unitmeta,"urb1","maxVal","99999")
	umswe.applyslk(unitmeta,"urb2","maxVal","99999")
	umswe.applyslk(unitmeta,"ua1s","maxVal","99999")
	umswe.applyslk(unitmeta,"ua2s","maxVal","99999")
	umswe.applyslk(unitmeta,"usd1","maxVal","99999")
	umswe.applyslk(unitmeta,"usd2","maxVal","99999")
	umswe.applyslk(unitmeta,"usr1","maxVal","99999")
	umswe.applyslk(unitmeta,"usr2","maxVal","99999")
	umswe.applyslk(unitmeta,"utc1","maxVal","99999")
	umswe.applyslk(unitmeta,"utc2","maxVal","99999")
	-- useHero
	umswe.applyslk(unitmeta,"ucua","useHero","1")
	umswe.applyslk(unitmeta,"ucun","useHero","1")
	umswe.applyslk(unitmeta,"ucut","useHero","1")
	umswe.applyslk(unitmeta,"umki","useHero","1")
	umswe.applyslk(unitmeta,"ures","useHero","1")
	umswe.applyslk(unitmeta,"urev","useHero","1")
	umswe.applyslk(unitmeta,"uupt","useHero","1")
	umswe.applyslk(unitmeta,"upap","useHero","1")
	umswe.applyslk(unitmeta,"upar","useHero","1")
	umswe.applyslk(unitmeta,"upat","useHero","1")
	umswe.applyslk(unitmeta,"upaw","useHero","1")
	-- useUnit
	umswe.applyslk(unitmeta,"umki","useUnit","1")
	umswe.applyslk(unitmeta,"ures","useUnit","1")
	umswe.applyslk(unitmeta,"urev","useUnit","1")
	umswe.applyslk(unitmeta,"utra","useUnit","1")
	umswe.applyslk(unitmeta,"uupt","useUnit","1")
	umswe.applyslk(unitmeta,"upap","useUnit","1")
	umswe.applyslk(unitmeta,"upar","useUnit","1")
	umswe.applyslk(unitmeta,"upat","useUnit","1")
	umswe.applyslk(unitmeta,"upaw","useUnit","1")
	-- useItem
	umswe.applyslk(unitmeta,"unsf","useItem","1")

	-- also enable optional modules if they're checked
	if umspathing then
		umswe.runscript("umswe\\umswepathing.lua")
	end
	if umstiles then
		umswe.runscript("umswe\\umswetilesets.lua")
	end
	if umscategories then
		umswe.runscript("umswe\\umswecategories.lua")
	end
	
else -- disable
	
	umswe.deletefile("UI\\WorldEditStrings.txt")
	umswe.deletefile("UI\\WorldEditLayout.txt")
	umswe.deletefile("UI\\MiscData.txt")
	umswe.deletefile("UI\\WorldEditData.txt")
	umswe.deletefile("Units\\UnitUI.slk")
	umswe.deletefile("Units\\AbilityData.slk")
	umswe.deletefile("Units\\UpgradeMetaData.slk")
	umswe.deletefile("Units\\UpgradeEffectMetaData.slk")
	umswe.deletefile("Doodads\\DoodadMetaData.slk")
	umswe.deletefile("Units\\DestructableMetaData.slk")
	umswe.deletefile("Units\\AbilityBuffMetaData.slk")
	umswe.deletefile("UI\\SkinMetaData.slk")
	umswe.deletefile("Units\\MiscMetaData.slk")
	umswe.deletefile("Units\\AbilityMetaData.slk")
	umswe.deletefile("Units\\UnitMetaData.slk")
	
	-- also disable optional modules just in case
	umswe.deletefile("TerrainArt\\Terrain.slk")
	umswe.deletefile("Units\\MiscGame.txt")
	umswe.deletefile("Units\\UnitBalance.slk")
	umswe.deletefile("Units\\DestructableData.slk")
	-- umswe.deletefile("Doodads\\Doodads.slk")
	
end

-- these are part of umswecore but in separate files
umswe.runscript("umswe\\umswetriggers.lua")
umswe.runscript("umswe\\umsweimports.lua")
