//Header
//! import "Header\Basic.j"
//! import "Header\Constants.j"
//! import "Header\Loading.j"
//! import "Header\Primitive.j"

//! import "Header\Math.j"

//! import "Header\Memory.j"

//! import "Header\Model.j"
//! import "Header\Preload.j"

//! import "Header\BoolExpr.j"
//! import "Header\Buff.j"
//! import "Header\Dialog.j"
//! import "Header\LimitOp.j"
//! import "Header\Multiboard.j"
//! import "Header\Region.j"
//! import "Header\Timer.j"
//! import "Header\Trigger.j"
//! import "Header\WeatherEffect.j"

//! import "Header\Event.j"
//! import "Header\Group.j"
//! import "Header\Spot.j"

//! import "Header\EventCombination.j"
//! import "Header\Order.j"
//! import "Header\StringData.j"

//! import "Header\Destructable.j"
//! import "Header\ItemType.j"
//! import "Header\Item.j"
//! import "Header\ItemObjectCreation.j"
//! import "Header\Misc.j"
//! import "Header\User.j"

//! import "Header\Camera.j"
//! import "Header\Sound.j"
//! import "Header\TextTag.j"

//! import "Header\UnitType.j"
//! import "Header\Unit.j"
//! import "Header\UnitObjectCreation.j"

//! import "Header\Effect.j"
//! import "Header\Game.j"
//! import "Header\Lightning.j"
//! import "Header\Missile.j"
//! import "Header\Spell.j"
//! import "Header\SpellObjectCreation.j"
//Commands
//! import "Commands\CharacterSpeech.j"
//Misc
//! import "Misc\ActUpgrades.j"
//! import "Misc\AfterIntro.j"
//! import "Misc\Artifact.j"
//! import "Misc\BrazierOracle.j"
//! import "Misc\CameraQuickPosition.j"
//! import "Misc\DefenderSpawn.j"
//! import "Misc\Difficulty.j"
//! import "Misc\Drop.j"
//! import "Misc\Explosive.j"
//! import "Misc\GoldCoin.j"
//! import "Misc\HeroRevival.j"
//! import "Misc\Hint.j"
//! import "Misc\HorseRide.j"
//! import "Misc\Infoboard.j"
//! import "Misc\Infocard.j"
//! import "Misc\Lumber.j"
//! import "Misc\Nullboard.j"
//! import "Misc\Rune.j"
//! import "Misc\Snowmen.j"
//! import "Misc\SpellPurchase.j"
//! import "Misc\UnitNameTag.j"
//! import "Misc\VictoryRush.j"
//! import "Misc\Waypoint.j"
//! import "Misc\Zoom.j"
//! import "Misc\rpgcam.j"
	//CreepBuffs
	//! import "Misc\CreepBuffs\MarkOfThePaw.j"

//! import "Misc\Act.j"
//! import "Misc\HeroSelection.j"
//! import "Misc\Intro.j"
//! import "Misc\Level.j"
//! import "Misc\OptionsBoard.j"
//! import "Misc\UnitStatus.j"

//! import "Misc\CreepSet.j"
//! import "Misc\Spawn.j"
//Speeches
//! import "Speeches\AxeFighter.j"
//! import "Speeches\Balduir.j"
//Spells
//! import "Spells\ArcticBlink.j"
//! import "Spells\BigHealingWave.j"
//! import "Spells\BurnLumber.j"
//! import "Spells\BurningSpirit.j"
//! import "Spells\BurningSpiritMeteorite.j"
//! import "Spells\CoreFusion.j"
//! import "Spells\DarkAttack.j"
//! import "Spells\FountainAura.j"
//! import "Spells\FountainHeal.j"
//! import "Spells\FrostAttack.j"
//! import "Spells\Invisibility.j"
//! import "Spells\Invulnerability.j"
//! import "Spells\Lapidation.j"
//! import "Spells\LightningAttack.j"
//! import "Spells\RefreshMana.j"
//! import "Spells\RevealAura.j"
//! import "Spells\TorchLight.j"
	//Act1
	//! import "Spells\Act1\Boost.j"
	//! import "Spells\Act1\ChaosBall.j"
	//! import "Spells\Act1\EnergyCharge.j"
	//! import "Spells\Act1\FuzzyAttack.j"
	//! import "Spells\Act1\GreenNova.j"
	//! import "Spells\Act1\Heal.j"
	//! import "Spells\Act1\HealExplosion.j"
	//! import "Spells\Act1\IceArrows.j"
	//! import "Spells\Act1\LightningShield.j"
	//! import "Spells\Act1\LunarRestoration.j"
	//! import "Spells\Act1\Purge.j"
	//! import "Spells\Act1\SoakingPoison.j"
	//! import "Spells\Act1\Stampede.j"
	//Act2
	//! import "Spells\Act2\Barrage.j"
	//! import "Spells\Act2\BouncyBomb.j"
	//! import "Spells\Act2\BurningOil.j"
	//! import "Spells\Act2\ChainLightning.j"
	//! import "Spells\Act2\Cleavage.j"
	//! import "Spells\Act2\ColdResistance.j"
	//! import "Spells\Act2\DeathAxe.j"
	//! import "Spells\Act2\DrumRoll.j"
	//! import "Spells\Act2\EnvenomedSpears.j"
	//! import "Spells\Act2\Knockout.j"
	//! import "Spells\Act2\Medipack.j"
	//! import "Spells\Act2\MutingShout.j"
	//! import "Spells\Act2\Realplex.j"
	//! import "Spells\Act2\SerpentWard.j"
	//! import "Spells\Act2\SpiritWolves.j"
	//! import "Spells\Act2\Stormbolt.j"
	//! import "Spells\Act2\SummonMinions.j"
	//Hero
	//! import "Spells\Hero\ArcticWolf.j"
	//! import "Spells\Hero\Amaterasu.j"
	//! import "Spells\Hero\Avatar.j"
	//! import "Spells\Hero\BattleRage.j"
	//! import "Spells\Hero\Bubble.j"
	//! import "Spells\Hero\Conflagration.j"
	//! import "Spells\Hero\Crippling.j"
	//! import "Spells\Hero\DeprivingShock.j"
	//! import "Spells\Hero\Doppelganger.j"
	//! import "Spells\Hero\EmphaticBite.j"
	//! import "Spells\Hero\FairysTears.j"
	//! import "Spells\Hero\GarmentsOfTheSalamander.j"
	//! import "Spells\Hero\HandOfNature.j"
	//! import "Spells\Hero\HopNDrop.j"
	//! import "Spells\Hero\Infection.j"
	//! import "Spells\Hero\KhakiRecovery.j"
	//! import "Spells\Hero\ManaLaser.j"
	//! import "Spells\Hero\NegationWave.j"
	//! import "Spells\Hero\PandaPaw.j"
	//! import "Spells\Hero\RazorBlade.j"
	//! import "Spells\Hero\RelentlessShiver.j"
	//! import "Spells\Hero\RigorMortis.j"
	//! import "Spells\Hero\SakeBomb.j"
	//! import "Spells\Hero\SleepingDraft.j"
	//! import "Spells\Hero\SummonPolarBear.j"
	//! import "Spells\Hero\Susanoo.j"
	//! import "Spells\Hero\TempestStrike.j"
	//! import "Spells\Hero\Tsukuyomi.j"
	//! import "Spells\Hero\WanShroud.j"
	//! import "Spells\Hero\WaterBindings.j"
	//! import "Spells\Hero\Zodiac.j"
	//Artifacts
	//! import "Spells\Artifacts\BatSwarm.j"
	//! import "Spells\Artifacts\MagicBottle.j"
	//! import "Spells\Artifacts\RedwoodValkyrie.j"
	//! import "Spells\Artifacts\SapphireblueDagger.j"
	//! import "Spells\Artifacts\SilentBoots.j"
	//! import "Spells\Artifacts\TaintedLeaf.j"
	//! import "Spells\Artifacts\Thunderbringer.j"
	//! import "Spells\Artifacts\VioletEarring.j"
	//! import "Spells\Artifacts\Vomit.j"
	//! import "Spells\Artifacts\WhiteStaff.j"
	//Purchasable
	//! import "Spells\Purchasable\Barrier.j"
	//! import "Spells\Purchasable\Blizzard.j"
	//! import "Spells\Purchasable\ChillyBreath.j"
	//! import "Spells\Purchasable\FlameTongue.j"
	//! import "Spells\Purchasable\Fireball.j"
	//! import "Spells\Purchasable\FrozenStar.j"
	//! import "Spells\Purchasable\GhostSword.j"
	//! import "Spells\Purchasable\HeatExplosion.j"
	//! import "Spells\Purchasable\IceBlock.j"
	//! import "Spells\Purchasable\Severance.j"
	//! import "Spells\Purchasable\SnowySphere.j"
	//! import "Spells\Purchasable\VividMeteor.j"
	//! import "Spells\Purchasable\WarmthMagnetism.j"
	//Item
	//! import "Spells\Item\EmergencyProvisions.j"
	//! import "Spells\Item\FireWater.j"
	//! import "Spells\Item\HerbalOintment.j"
	//! import "Spells\Item\IceTea.j"
	//! import "Spells\Item\Meat.j"
	//! import "Spells\Item\TropicalRainbow.j"
		//Act1
		//! import "Spells\Item\Act1\BoomerangStone.j"
		//! import "Spells\Item\Act1\EyeOfTheFlame.j"
		//! import "Spells\Item\Act1\ScrollOfProtection.j"
		//! import "Spells\Item\Act1\TeleportScroll.j"
		//Act2
//Items
//! import "Items\MeteoriteShard.j"
	//Act1
	//! import "Items\Act1\Mallet.j"
	//! import "Items\Act1\PenguinFeather.j"
	//! import "Items\Act1\RabbitsFoot.j"
	//! import "Items\Act1\RamblersStick.j"
	//Act2
	//! import "Items\Act2\GruntAxe.j"
	//! import "Items\Act2\RobynsHood.j"
	//Act3
	//! import "Items\Act3\ElfinDagger.j"
	//! import "Items\Act3\SpearOfTheDefender.j"
//System
//! import "System\Meteorite.j"
//Units
//! import "Units\FlyingPenguin.j"
//! import "Units\Library.j"
//! import "Units\Sebastian.j"
//AI
//! import "AI\Boost.j"
//! import "AI\BouncyBomb.j"
//! import "AI\BurningSpirit.j"
//! import "AI\ChaosBall.j"
//! import "AI\Heal.j"
//! import "AI\HealExplosion.j"
//! import "AI\Knockout.j"
//! import "AI\Medipack.j"
//! import "AI\Purge.j"
	//Header
	//! import "AI\Header\CastSpell.j"

//Init
//! import "Init\AI.j"
//! import "Init\Commands.j"
//! import "Init\Header.j"
//! import "Init\Items.j"
//! import "Init\Misc.j"
//! import "Init\Other.j"
//! import "Init\Speeches.j"
//! import "Init\Spells.j"
//! import "Init\Units.j"

//! import "Init\Main.j"
//Debug
//! import "Debug\loadmem.j"
//! import "Debug\say.j"
//! import "Debug\setid.j"
//! import "Debug\sethp.j"
//! import "Debug\setlvl.j"
//! import "Debug\memtabletest.j"
//! import "Debug\herospell.j"